name: torsync

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: torsync-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - ./prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - torsync

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: torsync-flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Dhaka
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - torsync

networks:
  torsync:
    name: torsync
